data_dir: .\data # after jy's dataset path change
batch_size: 1
wandb: False
name: ex # wandb run name, model save folder name
model_path:  microsoft/trocr-small-stage1 # user's pretrained weight or hugginface model name
processor_path: microsoft/trocr-small-stage1 # user's pretrained processor(must save processor) or hugginface model
mode: val # val or test
dataset_type: 140k

# fixed parameter
max_length_token: 100
report_step: 100
seed: 1004
vocab_size: 600