data_dir: ./data # after jy's dataset path change
batch_size: 16
num_epoch: 5
wandb: True
name: ex # wandb run name, model save folder name
model_path:  microsoft/trocr-small-stage1 # user's pretrained weight or hugginface model name

# fixed parameter
max_length_token: 100
report_step: 100
seed: 1004
vocab_size: 600